jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${SECRET}
  access:
    header: Authorization
    expiration: 3600
  refresh:
    header: Authorization-Refresh
    expiration: 86400
